# Generated by Django 5.1.1 on 2024-12-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='FormSubmission',
        ),
        migrations.DeleteModel(
            name='FullWidthImage',
        ),
        migrations.DeleteModel(
            name='MediaItem',
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
