# Generated by Django 5.1.1 on 2024-12-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_order_location_order_lattitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
